### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [1]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [60]:
### code here
import numpy as np
print("An array of 10 zeros:")
a=np.zeros(10)
print(a)
print("An array of 10 ones:")
b=np.ones(10)
print(b)
print("An array of 10 fives:")
c=[5.]*10
d=np.array(c)
print(d)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
## sample output

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [2]:
### code here
import numpy as np
arr=np.arange(30,71)
print("Array of the integers from 30 to 70")
print(arr)


Array of the integers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
### sample output

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [3]:
### code here
import numpy as np
x=np.arange(10,50)
print("Array of all even integers from 10 to 50")
y=x[0:40:2]
print(y)

Array of all even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
## sample output


Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [109]:
### code here
import numpy as np
x=np.eye(3)
print("3x3 matrix:")
print(x)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
## sample output

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [137]:
### code here
import numpy as np
a=np.random.rand(1)
print("Random number between 0 and 1:")
print(a)

Random number between 0 and 1:
[0.52616967]


In [ ]:
## sample output

Random number between 0 and 1:
[0.40400053]


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [160]:
## code here
import numpy as np
a=np.random.randn(15)
print("15 random numbers from a standard normal distribution:")
print(a)

15 random numbers from a standard normal distribution:
[ 0.67483167 -0.46167606  1.86768631  0.0137022  -1.46292676  0.19968688
  0.81142519  0.59740546  0.78190866 -1.17779672 -0.09392445 -0.18519098
  1.26707242 -1.21383738 -0.04249538]


In [159]:
## sample output

15 random numbers from a standard normal distribution:
[ 0.67353234  0.31892142 -0.74752946 -0.7241196  -0.22232638 -0.60349422
  0.02214188  1.2589063  -1.65333685  0.54973924  0.59506621 -0.50287033
 -0.65601357  0.1789475   0.42012843]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [22]:
## code here
import numpy as np
a=np.array([10,11,12,13,14,15,16,17,18,19,20,21]).reshape(3,4)
print("Original array:")
print(a)
print("Each element of the array is:")
for i in range(10,22):
    print(i,end=' ')
    

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

In [166]:
## sample output

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [27]:
## code here
import numpy as np
a=np.array([1,8,3,5])
b=np.array([10,1,4,10])
print("Vector-1")
print(a)
print("Vector-2")
print(b)
print("Multiply the values of two said vectors:")
print(a*b)

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


In [ ]:
## sample output

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [9]:
### code here
import numpy as np
x=np.arange(12,38)
print("Original array:")
print(x)
print("Reverse array:")
print(x[:-36:-1])

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


## sample output

##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [31]:
## code here
import numpy as np
x=np.diag([1,2,3,4,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
## sample output

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [51]:
## code here
import numpy as np
a=np.array([[0,1],[2,3]])
print("Original array:")
print(a)
print("Sum of all elements:")
x=a.sum()
print(x)
c=np.sum(a,axis=0)
d=np.sum(a,axis=1)
print("Sum of each column:")
print(c)
print("Sum of each row:")
print(d)


Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


In [ ]:
## sample output

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [63]:
## code here 
a=np.array([4,5])
b=np.array([7,10])
print("Original Vectors:")
print(a)
print(b)
print("Inner product of said vectors:")
print(np.dot(a,b))


Original Vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78


In [56]:
## sample output

Original Vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78
